print('hi...')
print("hi.....")
print('''
      adaaaaaaaadad
        dadadadwasd
      dadadaawdwsad
            dadadaasdw
      ''')
print(323)
print(3123.434)
print(True)
print(False)
print(242+424-45)